Update snowflake-tests.yml

diff --git a/.github/workflows/snowflake-tests.yml b/.github/workflows/snowflake-tests.yml
--- a/.github/workflows/snowflake-tests.yml
+++ b/.github/workflows/snowflake-tests.yml
@@ -53,6 +53,17 @@ jobs:
           echo "Test for COLUMN_NULL_COUNT failed.";
           exit 1;
         fi
+
+        echo "Checking for NEGATIVE_METRIC_COUNT value..."
+        if grep -q '|                 0 |' test_results.txt; then
+          echo "Test for NEGATIVE_METRIC_COUNT passed.";
+        else
+          echo "Test for NEGATIVE_METRIC_COUNT failed.";
+          echo "Details:";
+          grep '| NEGATIVE_METRIC_COUNT |' test_results.txt || echo "No match found for '| NEGATIVE_METRIC_COUNT |'"
+          exit 1;
+        fi
+        
         # if grep -q 'negative_metric_count,0' test_results.txt; then
         #   echo "Test for negative_metric_count passed.";
         # else
