Update snowflake-tests.yml

diff --git a/.github/workflows/snowflake-tests.yml b/.github/workflows/snowflake-tests.yml
--- a/.github/workflows/snowflake-tests.yml
+++ b/.github/workflows/snowflake-tests.yml
@@ -49,20 +49,20 @@ jobs:
         echo "Contents of test_results.txt:"
         cat test_results.txt
 
-        echo "Checking for column_null_count..."
-        if grep -q 'column_null_count' test_results.txt; then
-          echo "Pattern 'column_null_count' found.";
+        echo "Checking for COLUMN_NULL_COUNT..."
+        if grep -q '| COLUMN_NULL_COUNT |' test_results.txt; then
+          echo "Pattern 'COLUMN_NULL_COUNT' found.";
         else
-          echo "Pattern 'column_null_count' not found.";
+          echo "Pattern 'COLUMN_NULL_COUNT' not found.";
         fi
 
-        echo "Checking for column_null_count,1..."
-        if grep -q 'column_null_count,1' test_results.txt; then
-          echo "Test for column_null_count passed.";
+        echo "Checking for COLUMN_NULL_COUNT value..."
+        if grep -q '|                 1 |' test_results.txt; then
+          echo "Test for COLUMN_NULL_COUNT passed.";
         else
-          echo "Test for column_null_count failed.";
+          echo "Test for COLUMN_NULL_COUNT failed.";
           echo "Details:";
-          grep 'column_null_count' test_results.txt || echo "No match found for 'column_null_count'"
+          grep '| COLUMN_NULL_COUNT |' test_results.txt || echo "No match found for '| COLUMN_NULL_COUNT |'"
           exit 1;
         fi
         # if grep -q 'negative_metric_count,0' test_results.txt; then
