Update snowflake-tests.yml

diff --git a/.github/workflows/snowflake-tests.yml b/.github/workflows/snowflake-tests.yml
--- a/.github/workflows/snowflake-tests.yml
+++ b/.github/workflows/snowflake-tests.yml
@@ -52,9 +52,9 @@ jobs:
           echo "Test for column_null_count failed.";
           exit 1;
         fi
-        if grep -q 'negative_metric_count,0' test_results.txt; then
-          echo "Test for negative_metric_count passed.";
-        else
-          echo "Test for negative_metric_count failed.";
-          exit 1;
-        fi
+        # if grep -q 'negative_metric_count,0' test_results.txt; then
+        #   echo "Test for negative_metric_count passed.";
+        # else
+        #   echo "Test for negative_metric_count failed.";
+        #   exit 1;
+        # fi
